import React, { useState } from 'react';
import { useLanguage } from '../i18n/LanguageContext';
import { Card } from '../components/Card';
import { Badge } from '../components/Badge';
import { Button } from '../components/Button';
import { CodeBlock } from '../components/CodeBlock';
import { SEOHead } from '../components/SEOHead';
import {
  Cpu,
  Activity,
  Layers,
  CheckCircle2,
  Code,
  ArrowRight,
  ExternalLink,
  Zap,
  TrendingUp,
} from 'lucide-react';

export const AnalysisPage: React.FC = () => {
  const { language } = useLanguage();
  const [selectedScriptType, setSelectedScriptType] = useState<'tcl' | 'python'>('tcl');

  const tclExample = `# OpenSees Linear Static Analysis Generated by TSA
model BasicBuilder -ndm 3 -ndf 6

# Nodes (X, Y, Z)
node 1   0.0   0.0   0.0
node 2   6.0   0.0   0.0
node 3   0.0   0.0   3.5
node 4   6.0   0.0   3.5

# Boundary Restraints (Fixed Bases)
fix 1  1 1 1 1 1 1
fix 2  1 1 1 1 1 1

# Material & Geometric Transformation
geomTransf Linear 1  0 0 1
# Section HEA 240 (E = 2.1e11 Pa, G = 8.1e10 Pa, A = 7.68e-3 m2, Iz = 7.76e-5 m4, Iy = 2.77e-5 m4)
element elasticBeamColumn 1  1 3  7.68e-3 2.1e11 8.1e10 4.15e-7 2.77e-5 7.76e-5 1
element elasticBeamColumn 2  2 4  7.68e-3 2.1e11 8.1e10 4.15e-7 2.77e-5 7.76e-5 1
# Beam IPE 300
element elasticBeamColumn 3  3 4  5.38e-3 2.1e11 8.1e10 2.01e-7 6.04e-6 8.36e-5 1

# Load Pattern (Gravity + Lateral Wind)
pattern Plain 1 Linear {
    eleLoad -ele 3 -type -beamUniform -25.0 0.0
    load 3  15.0 0.0 0.0  0.0 0.0 0.0
}

# Solver Strategy
system BandGeneral
numberer RCM
constraints Plain
integrator LoadControl 1.0
algorithm Linear
analysis Static
analyze 1
puts "TSA_SOLVE_SUCCESS"`;

  const pythonExample = `import openseespy.opensees as ops

# OpenSeesPy Model Generated by TSA
ops.wipe()
ops.model('basic', '-ndm', 3, '-ndf', 6)

# Nodal Coordinates
ops.node(1, 0.0, 0.0, 0.0)
ops.node(2, 6.0, 0.0, 0.0)
ops.node(3, 0.0, 0.0, 3.5)
ops.node(4, 6.0, 0.0, 3.5)

# Boundary Conditions
ops.fix(1, 1, 1, 1, 1, 1, 1)
ops.fix(2, 1, 1, 1, 1, 1, 1)

# Transformations & Elements
ops.geomTransf('Linear', 1, 0, 0, 1)
ops.element('elasticBeamColumn', 1, 1, 3, 7.68e-3, 2.1e11, 8.1e10, 4.15e-7, 2.77e-5, 7.76e-5, 1)
ops.element('elasticBeamColumn', 2, 2, 4, 7.68e-3, 2.1e11, 8.1e10, 4.15e-7, 2.77e-5, 7.76e-5, 1)
ops.element('elasticBeamColumn', 3, 3, 4, 5.38e-3, 2.1e11, 8.1e10, 2.01e-7, 6.04e-6, 8.36e-5, 1)

# Linear Static Solution
ops.system('BandGeneral')
ops.numberer('RCM')
ops.constraints('Plain')
ops.integrator('LoadControl', 1.0)
ops.algorithm('Linear')
ops.analysis('Static')
ops.analyze(1)
print("TSA_OPENSEESPY_SUCCESS")`;

  return (
    <div className="w-full py-12 lg:py-16">
      <SEOHead
        title={language === 'fr' ? 'Analyse & OpenSees' : 'Analysis & OpenSees'}
        description={
          language === 'fr'
            ? 'Intégration du moteur d\'analyse par éléments finis OpenSees dans TSA : formulation matricielle, chaîne de calcul et post-traitement.'
            : 'OpenSees finite element analysis engine integration in TSA: matrix formulation, computational pipeline, and post-processing.'
        }
      />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="max-w-3xl mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 text-xs font-semibold text-tsa-cyan-500 dark:text-tsa-cyan-300 mb-3">
            <Cpu className="w-3.5 h-3.5" />
            <span>{language === 'fr' ? 'Moteur Scientifique de Calcul' : 'Scientific Computational Engine'}</span>
          </div>
          <h1 className="text-4xl sm:text-5xl font-extrabold text-slate-900 dark:text-white tracking-tight">
            {language === 'fr' ? 'Analyse par Éléments Finis & OpenSees' : 'Finite Element Analysis & OpenSees'}
          </h1>
          <p className="mt-4 text-base sm:text-lg text-slate-600 dark:text-slate-400 leading-relaxed">
            {language === 'fr'
              ? 'TSA associe une modélisation CAO tridimensionnelle intuitive à la rigueur de calcul d\'OpenSees, le solveur d\'éléments finis développé par l\'Université de Californie à Berkeley.'
              : 'TSA bridges intuitive 3D CAD modeling with the analytical rigor of OpenSees, the world-renowned finite element solver developed at UC Berkeley.'}
          </p>
        </div>

        {/* Workflow Diagram & Steps */}
        <div className="mb-16">
          <div className="text-xs font-mono font-semibold uppercase tracking-wider text-tsa-blue-600 dark:text-tsa-cyan-400 mb-2">
            {language === 'fr' ? 'Architecture du Pipeline de Calcul' : 'Calculation Pipeline Architecture'}
          </div>
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white mb-6">
            {language === 'fr' ? 'Du Modèle CAO aux Résultats Réglementaires' : 'From CAD Model to Certified Results'}
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
            {[
              {
                step: '01',
                titleEn: 'TSA Model',
                titleFr: 'Modèle TSA',
                descEn: 'Physical structural model with beams, columns, slabs, and loads.',
                descFr: 'Modèle physique avec poutres, poteaux, dalles et charges.',
              },
              {
                step: '02',
                titleEn: 'Discretization',
                titleFr: 'Discrétisation',
                descEn: 'Automatic 1D member division and 2D surface plate meshing.',
                descFr: 'Découpage des barres et maillage éléments finis des surfaces.',
              },
              {
                step: '03',
                titleEn: 'OpenSees Assembly',
                titleFr: 'Assemblage OpenSees',
                descEn: 'Compilation of global stiffness matrix [K] and load vector {F}.',
                descFr: 'Compilation de la matrice de rigidité globale [K] et vecteur {F}.',
              },
              {
                step: '04',
                titleEn: 'Solver Run',
                titleFr: 'Exécution Solveur',
                descEn: 'High-speed sparse matrix inversion and iterative solver.',
                descFr: 'Inversion de matrices creuses haute performance et solveur.',
              },
              {
                step: '05',
                titleEn: 'TSA Results',
                titleFr: 'Résultats TSA',
                descEn: '3D deformed shape, N-V-M diagrams, and equilibrium checks.',
                descFr: 'Déformée 3D, diagrammes N-V-M et bilan d\'équilibre statique.',
              },
            ].map((st, idx) => (
              <Card key={idx} className="p-5 flex flex-col justify-between">
                <div>
                  <span className="text-2xl font-black font-mono text-tsa-blue-600/40 dark:text-tsa-cyan-400/40 mb-2 block">
                    {st.step}
                  </span>
                  <h3 className="text-base font-bold text-slate-900 dark:text-white mb-2">
                    {language === 'fr' ? st.titleFr : st.titleEn}
                  </h3>
                  <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                    {language === 'fr' ? st.descFr : st.descEn}
                  </p>
                </div>
              </Card>
            ))}
          </div>
        </div>

        {/* Matrix Equation Section */}
        <div className="p-8 rounded-2xl bg-gradient-to-br from-slate-900 via-tsa-navy-900 to-slate-950 border border-slate-800 text-white mb-16 shadow-xl">
          <div className="max-w-3xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/20 text-xs font-mono text-tsa-cyan-400 mb-4">
              <span>FUNDAMENTAL EQUILIBRIUM EQUATION</span>
            </div>
            <h3 className="text-2xl sm:text-3xl font-mono font-bold text-white mb-4">
              [K] · {'{U}'} = {'{F}'}
            </h3>
            <p className="text-sm sm:text-base text-slate-300 leading-relaxed mb-6">
              {language === 'fr'
                ? 'TSA assemble rigoureusement la matrice de rigidité globale [K] à partir des matrices de rigidité élémentaires 12×12 des barres spatiales et des matrices de coques MITC4. OpenSees résout le système avec gestion avancée des conditionnements et singularités.'
                : 'TSA rigorously compiles the global stiffness matrix [K] from local 12×12 spatial beam-column matrices and MITC4 shell formulations. OpenSees computes the unknown displacement vector {U} with advanced sparsity handling.'}
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs font-mono">
              <div className="p-3 rounded-lg bg-slate-950/70 border border-slate-800">
                <span className="text-tsa-cyan-400 font-bold block mb-1">[K] Stiffness Matrix</span>
                <span className="text-slate-400">Condensed sparse global matrix with 6 DOFs per node.</span>
              </div>
              <div className="p-3 rounded-lg bg-slate-950/70 border border-slate-800">
                <span className="text-emerald-400 font-bold block mb-1">{'{U}'} Displacement Vector</span>
                <span className="text-slate-400">Translations (Ux, Uy, Uz) & Rotations (Rx, Ry, Rz).</span>
              </div>
              <div className="p-3 rounded-lg bg-slate-950/70 border border-slate-800">
                <span className="text-amber-400 font-bold block mb-1">{'{F}'} Action Vector</span>
                <span className="text-slate-400">Dead, live, lateral wind, and seismic inertial loads.</span>
              </div>
            </div>
          </div>
        </div>

        {/* Code Generator Showcase */}
        <div className="mb-16">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4">
            <div>
              <div className="text-xs font-mono font-semibold uppercase tracking-wider text-tsa-blue-600 dark:text-tsa-cyan-400 mb-1">
                {language === 'fr' ? 'Génération de Script Déterministe' : 'Deterministic Script Generation'}
              </div>
              <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white">
                {language === 'fr' ? 'Passerelle OpenSees TCL / OpenSeesPy' : 'OpenSees TCL & OpenSeesPy Bridge'}
              </h2>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={() => setSelectedScriptType('tcl')}
                className={`px-3 py-1.5 rounded-lg text-xs font-mono font-semibold transition-colors ${
                  selectedScriptType === 'tcl'
                    ? 'bg-tsa-blue-600 text-white'
                    : 'bg-slate-200 dark:bg-slate-800 text-slate-600 dark:text-slate-400'
                }`}
              >
                OpenSees TCL
              </button>
              <button
                onClick={() => setSelectedScriptType('python')}
                className={`px-3 py-1.5 rounded-lg text-xs font-mono font-semibold transition-colors ${
                  selectedScriptType === 'python'
                    ? 'bg-tsa-blue-600 text-white'
                    : 'bg-slate-200 dark:bg-slate-800 text-slate-600 dark:text-slate-400'
                }`}
              >
                OpenSeesPy (Python)
              </button>
            </div>
          </div>

          <p className="text-sm text-slate-600 dark:text-slate-400 mb-4">
            {language === 'fr'
              ? 'TSA génère des scripts d\'analyse propres, auditables et reproductibles que les ingénieurs et chercheurs peuvent exporter et réexécuter indépendamment.'
              : 'TSA generates clean, auditable, and reproducible calculation scripts that engineers and researchers can inspect, export, and rerun independently.'}
          </p>

          <CodeBlock
            code={selectedScriptType === 'tcl' ? tclExample : pythonExample}
            language={selectedScriptType === 'tcl' ? 'tcl' : 'python'}
            filename={selectedScriptType === 'tcl' ? 'model_analysis.tcl' : 'model_analysis.py'}
            showLineNumbers
          />
        </div>

        {/* Third-Party Attribution Notice */}
        <div className="p-6 rounded-xl bg-slate-50 dark:bg-tsa-surface-card border border-slate-200 dark:border-slate-800 flex items-start gap-4">
          <div className="p-2 rounded-lg bg-blue-500/10 text-tsa-blue-600 dark:text-tsa-cyan-400 shrink-0">
            <ExternalLink className="w-5 h-5" />
          </div>
          <div>
            <h4 className="text-sm font-bold text-slate-900 dark:text-white mb-1">
              OpenSees Attribution & Governance
            </h4>
            <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
              OpenSees (Open System for Earthquake Engineering Simulation) is developed by the Pacific Earthquake Engineering Research (PEER) Center at the University of California, Berkeley. TSA interfaces with OpenSees in full respect of its license and academic attribution principles.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
