import { FeatureItem } from '../types';

export const featureItems: FeatureItem[] = [
  // --- Modélisation (Modeling) ---
  {
    id: 'mod-nodes',
    name: '3D Coordinate Nodes',
    nameFr: 'Nœuds tridimensionnels',
    category: 'modeling',
    status: 'AVAILABLE',
    descriptionEn: 'Spatial structural vertices supporting 6 degrees of freedom (DOF) with customizable boundary restraints and spring supports.',
    descriptionFr: 'Sommets spatiaux supportant 6 degrés de liberté (DDL) avec conditions d\'appuis paramétrables et liaisons élastiques.',
    tags: ['Core', 'Topology', '6-DOF'],
  },
  {
    id: 'mod-beams-cols',
    name: 'Beams & Columns (LinearElements)',
    nameFr: 'Poutres & Poteaux (Éléments Linéaires)',
    category: 'modeling',
    status: 'AVAILABLE',
    descriptionEn: 'Timoshenko and Euler-Bernoulli beam-column elements with section orientation, end releases (hinges), and rigid end offsets.',
    descriptionFr: 'Éléments barres Timoshenko et Euler-Bernoulli avec orientation locale, rotules d\'extrémités et zones rigides.',
    tags: ['LinearElement', 'Frames', 'Releases'],
  },
  {
    id: 'mod-slabs-walls',
    name: 'Slabs & Structural Walls',
    nameFr: 'Dalles & Voiles Porteurs',
    category: 'modeling',
    status: 'BETA',
    descriptionEn: '2D Surface elements for floor slabs, diaphragms, shear walls, and core walls with openings and variable thickness.',
    descriptionFr: 'Éléments de surface 2D pour planchers, diaphragmes et voiles de contreventement avec trémies et épaisseur variable.',
    tags: ['SurfaceElement', 'Diaphragms', 'Openings'],
  },
  {
    id: 'mod-foundations',
    name: 'Isolated & Strip Foundations',
    nameFr: 'Semelles isolées & filantes',
    category: 'modeling',
    status: 'IN_DEVELOPMENT',
    descriptionEn: 'Pad and continuous footings with soil interaction springs (Winkler bedding modulus) and punching shear checks.',
    descriptionFr: 'Semelles ponctuelles et continues avec modélisation du sol élastique (Winkler) et vérification du poinçonnement.',
    tags: ['Foundations', 'Soil-Structure', 'Winkler'],
  },
  {
    id: 'mod-cables-truss',
    name: 'Trusses & Tension Cables',
    nameFr: 'Treillis & Câbles de Tension',
    category: 'modeling',
    status: 'AVAILABLE',
    descriptionEn: 'Axial-only truss members and tension-only non-linear cable elements with pre-tensioning and catenary geometry builder.',
    descriptionFr: 'Barres articulées en traction-compression et câbles de haubanage non-linéaires avec prétension et chaînette.',
    tags: ['Cables', 'Truss', 'Nonlinear'],
  },
  {
    id: 'mod-workplanes',
    name: 'Interactive WorkPlanes & Grids',
    nameFr: 'Plans de Travail (WorkPlanes) & Grilles',
    category: 'modeling',
    status: 'AVAILABLE',
    descriptionEn: 'Arbitrary 3D drafting planes, Cartesian & Cylindrical multi-level grids with automatic snapping and visual axes.',
    descriptionFr: 'Plans de construction 3D orientables, grilles cartésiennes et cylindriques multi-niveaux avec accrochage précis.',
    tags: ['WorkPlane', 'Grids', 'CAD-Snap'],
  },
  {
    id: 'mod-levels',
    name: 'Building Stories & Level Manager',
    nameFr: 'Gestionnaire d\'Étages & Niveaux',
    category: 'modeling',
    status: 'AVAILABLE',
    descriptionEn: 'Architectural story elevation management with automatic element association, inter-story drift tracking, and floor grouping.',
    descriptionFr: 'Gestion des niveaux et hauteurs d\'étages avec assignation automatique et contrôle des dérives d\'étages.',
    tags: ['Stories', 'Levels', 'Building'],
  },
  {
    id: 'mod-sections-mats',
    name: 'Parametric Sections & TSALib Materials',
    nameFr: 'Sections Paramétriques & Matériaux TSALib',
    category: 'modeling',
    status: 'AVAILABLE',
    descriptionEn: 'Standard steel catalogs (IPE, HEA, HEB, UPN, Pipes, Tubes), parametric RC shapes, and hot-reloadable TSALib dynamic libraries.',
    descriptionFr: 'Profilés métalliques normalisés, sections béton armé paramétriques et bibliothèques dynamiques rechargeables à chaud TSALib.',
    tags: ['Sections', 'TSALib', 'Materials'],
  },

  // --- CAO & Manipulation ---
  {
    id: 'cad-selection',
    name: 'Advanced 3D Selection & Filtering',
    nameFr: 'Sélection & Filtrage 3D Avancé',
    category: 'cad',
    status: 'AVAILABLE',
    descriptionEn: 'Window, crossing, box and lasso selection with immediate filtering by story, section, material, or element type.',
    descriptionFr: 'Sélection fenêtre, capture, et lasso avec filtrage instantané par étage, profilé, matériau ou type d\'élément.',
    tags: ['Selection', 'Filters', 'Viewer'],
  },
  {
    id: 'cad-transforms',
    name: 'Move, Copy, Rotate & Mirror',
    nameFr: 'Déplacement, Copie, Rotation & Miroir',
    category: 'cad',
    status: 'AVAILABLE',
    descriptionEn: 'Vector translation, multi-copy distribution along paths, 3D spatial rotation, and plane mirroring preserving structural loads.',
    descriptionFr: 'Translation vectorielle, duplication multiple linéaire, rotation spatiale et miroir avec conservation des charges.',
    tags: ['Transforms', 'Manipulation', '3D'],
  },
  {
    id: 'cad-snapping',
    name: 'Smart Object Snapping & Grips',
    nameFr: 'Accrochage Intelligent & Points d\'Accroche',
    category: 'cad',
    status: 'AVAILABLE',
    descriptionEn: 'Magnetic snap to nodes, element midpoints, intersections, perpendiculars, and parametric grip handle manipulation.',
    descriptionFr: 'Accrochage magnétique aux nœuds, milieux, intersections, perpendiculaires et poignées d\'édition géométrique.',
    tags: ['Snap', 'Grips', 'Precision'],
  },
  {
    id: 'cad-topology-tools',
    name: 'Trim, Extend, Split & Merge',
    nameFr: 'Ajuster, Prolonger, Scinder & Fusionner',
    category: 'cad',
    status: 'IN_DEVELOPMENT',
    descriptionEn: 'Interactive member trimming, extending to boundary planes, node-at-intersection splitting, and collinear merging.',
    descriptionFr: 'Ajustement de barres, prolongation jusqu\'à un plan de référence, découpage aux intersections et fusion d\'éléments alignés.',
    tags: ['Topology', 'Editing', 'CAD'],
  },
  {
    id: 'cad-undo-redo',
    name: 'Full Undo / Redo Command History',
    nameFr: 'Historique d\'Annulation (Undo/Redo)',
    category: 'cad',
    status: 'AVAILABLE',
    descriptionEn: 'State snapshot and command pattern architecture allowing infinite undo/redo across all geometry and load operations.',
    descriptionFr: 'Architecture par commandes et snapshots d\'état garantissant une annulation/rétablissement complète et sans faille.',
    tags: ['UndoRedo', 'State', 'Safety'],
  },

  // --- Analyse Structurale (Analysis) ---
  {
    id: 'ana-opensees-solver',
    name: 'OpenSees FEM Solver Integration',
    nameFr: 'Intégration du Solveur OpenSees',
    category: 'analysis',
    status: 'AVAILABLE',
    descriptionEn: 'Native bridging to the OpenSees finite element framework for linear static, modal, and non-linear dynamic computations.',
    descriptionFr: 'Passerelle native vers le moteur d\'éléments finis OpenSees pour le calcul statique linéaire, modal et dynamique.',
    tags: ['OpenSees', 'FEM', 'Solvers'],
  },
  {
    id: 'ana-loads',
    name: 'Load Cases & Action Combinations',
    nameFr: 'Cas de Charges & Combinaisons d\'Actions',
    category: 'analysis',
    status: 'AVAILABLE',
    descriptionEn: 'Nodal concentrated forces, uniform and trapezoidal member loads, surface pressure, and automatic Eurocode EN 1990 combination generator.',
    descriptionFr: 'Forces ponctuelles nodales, charges réparties trapézoïdales, pressions surfaciques et combinaisons automatisées selon l\'Eurocode 0.',
    tags: ['Loads', 'Combinations', 'Eurocodes'],
  },
  {
    id: 'ana-stiffness-matrix',
    name: 'Global Stiffness Matrix [K] Assembly',
    nameFr: 'Assemblage de la Matrice de Rigidité [K]',
    category: 'analysis',
    status: 'AVAILABLE',
    descriptionEn: 'Direct access to condensed structural stiffness matrices, condition number validation, and singularity diagnostics.',
    descriptionFr: 'Accès direct aux matrices de rigidité globales condensées, vérification du conditionnement et diagnostic de singularités.',
    tags: ['Matrix', 'Stiffness', 'Diagnostics'],
  },
  {
    id: 'ana-modal',
    name: 'Modal Eigenvalue & Vibration Frequencies',
    nameFr: 'Analyse Modale & Fréquences Propres',
    category: 'analysis',
    status: 'BETA',
    descriptionEn: 'Lanczos and subspace eigensolvers calculating natural frequencies, modal mass participation factors, and animated mode shapes.',
    descriptionFr: 'Calcul des fréquences propres, facteurs de participation massique modale et animation 3D des déformées modales.',
    tags: ['Modal', 'Dynamics', 'Seismic'],
  },
  {
    id: 'ana-nonlinear',
    name: 'Nonlinear Geometric (P-Delta) & Pushover',
    nameFr: 'Non-linéarité Géométrique (P-Delta) & Pushover',
    category: 'analysis',
    status: 'IN_DEVELOPMENT',
    descriptionEn: 'Second-order geometric effects (P-Delta), plastic hinge formulation, and non-linear static pushover capacity curves.',
    descriptionFr: 'Effets du second ordre (P-Delta), rotules plastiques concentrées et courbes de capacité pushover non-linéaires.',
    tags: ['P-Delta', 'Nonlinear', 'Capacity'],
  },

  // --- Maillage (Meshing) ---
  {
    id: 'mesh-auto',
    name: 'Automatic Surface Discretization',
    nameFr: 'Discrétisation Automatique de Surfaces',
    category: 'meshing',
    status: 'BETA',
    descriptionEn: 'Delaunay and Advancing Front algorithms generating quality triangular (T3/T6) and quadrilateral (Q4/Q8) shell meshes.',
    descriptionFr: 'Algorithmes de Delaunay et front montant générant des maillages coques triangulaires et quadrilatéraux de haute qualité.',
    tags: ['Meshing', 'Shells', 'Delaunay'],
  },
  {
    id: 'mesh-refinement',
    name: 'Local Mesh Refinement & Gradients',
    nameFr: 'Raffinement Local & Gradients de Maillage',
    category: 'meshing',
    status: 'IN_DEVELOPMENT',
    descriptionEn: 'Targeted element density control around column heads, re-entrant corners, slab openings, and concentrated load points.',
    descriptionFr: 'Contrôle ciblé de la densité de maillage autour des têtes de poteaux, angles rentrants, trémies et charges concentrées.',
    tags: ['Refinement', 'Adaptive', 'Stress-Concentration'],
  },
  {
    id: 'mesh-quality',
    name: 'Mesh Quality Control & Aspect Ratio Checks',
    nameFr: 'Contrôle Qualité & Vérification d\'Élancement',
    category: 'meshing',
    status: 'BETA',
    descriptionEn: 'Interactive visual heatmaps highlighting warped elements, high aspect ratio distortion, and Jacobian skew angles.',
    descriptionFr: 'Cartes de chaleur visuelles signalant les éléments gauchis, ratios d\'aspect excessifs et distorsions jacobiennes.',
    tags: ['Quality', 'Jacobian', 'Distortion'],
  },
  {
    id: 'mesh-compatibility',
    name: 'Beam-Shell Nodal Compatibility',
    nameFr: 'Compatibilité Nodale Poutre-Dalle',
    category: 'meshing',
    status: 'IN_DEVELOPMENT',
    descriptionEn: 'Automatic line constraint and intersection node snapping between 1D ribs and 2D slab plate meshes.',
    descriptionFr: 'Création automatique de nœuds d\'intersection et de compatibilité cinématique entre nervures 1D et dalles 2D.',
    tags: ['Compatibility', 'Ribs', 'Constraints'],
  },

  // --- Résultats & Post-Traitement (Results) ---
  {
    id: 'res-deformations',
    name: 'Nodal Displacements {U} & Deflections',
    nameFr: 'Déplacements Nodaux {U} & Flèches',
    category: 'results',
    status: 'AVAILABLE',
    descriptionEn: 'Full 3D translation (Ux, Uy, Uz) and rotation (Rx, Ry, Rz) vectors with animated scale multipliers and limit state checks.',
    descriptionFr: 'Vecteurs de déplacement 3D complets avec curseur d\'amplification dynamique et vérification des flèches limites (ELS).',
    tags: ['Displacements', 'Deflections', 'ELS'],
  },
  {
    id: 'res-diagrams',
    name: 'Internal Force Diagrams (N, Vy, Vz, Mt, My, Mz)',
    nameFr: 'Diagrammes d\'Efforts Internes (N, V, M)',
    category: 'results',
    status: 'AVAILABLE',
    descriptionEn: 'High-definition axial force, shear force, torsion, and bending moment curves directly rendered on 3D element axes.',
    descriptionFr: 'Tracé vectoriel précis des efforts normaux, tranchants, torsion et moments fléchissants directement sur les axes 3D.',
    tags: ['Moments', 'Shear', 'InternalForces'],
  },
  {
    id: 'res-reactions',
    name: 'Support Reaction Vectors & Equilibrium Checks',
    nameFr: 'Réactions d\'Appuis & Vérification de l\'Équilibre',
    category: 'results',
    status: 'AVAILABLE',
    descriptionEn: 'Graphical reaction arrows with automated global force balance verification (∑F = 0, ∑M = 0) ensuring solution integrity.',
    descriptionFr: 'Vecteurs graphiques de réactions et bilan automatisé des actions (∑F = 0, ∑M = 0) validant l\'équilibre statique.',
    tags: ['Reactions', 'Equilibrium', 'Validation'],
  },
  {
    id: 'res-stresses',
    name: 'Von Mises & Principal Stress Iso-surfaces',
    nameFr: 'Contraintes de Von Mises & Principales',
    category: 'results',
    status: 'BETA',
    descriptionEn: 'Color contour maps on shell elements for membrane stresses, bending moments (Mx, My, Mxy), and Von Mises yield criteria.',
    descriptionFr: 'Cartographies couleur sur les coques pour les contraintes de membrane, moments de flexion et critère d\'élasticité de Von Mises.',
    tags: ['VonMises', 'Stresses', 'Contour'],
  },
  {
    id: 'res-export',
    name: 'Structured Result Export (CSV, JSON, PDF)',
    nameFr: 'Export Structuré des Résultats (CSV, JSON, PDF)',
    category: 'results',
    status: 'IN_DEVELOPMENT',
    descriptionEn: 'Tabular export of extreme envelope values, governing load combinations, and calculation report sheets.',
    descriptionFr: 'Export tabulaire des enveloppes d\'efforts max/min, cas dimensionnants et fiches de synthèse de calcul.',
    tags: ['Export', 'Reports', 'Tables'],
  },
];
