import { PricingTier } from '../types';

export const pricingNotice = {
  en: 'Pricing and edition details are subject to change prior to commercial launch. Pre-release access is governed by the Community and Development program.',
  fr: 'Les tarifs et éditions sont sujets à modification avant le lancement commercial. L\'accès anticipé est régi par le programme Communautaire et de Développement.',
};

export const pricingTiers: PricingTier[] = [
  {
    id: 'community',
    name: 'Community',
    nameFr: 'Communauté',
    badgeEn: 'Free & Open Exploration',
    badgeFr: 'Gratuit & Découverte',
    priceEn: 'Free',
    priceFr: 'Gratuit',
    periodEn: 'Forever',
    periodFr: 'Pour toujours',
    descriptionEn: 'Full access to core modeling, OpenSees linear static analysis, and learning tools for students, researchers, and hobbyists.',
    descriptionFr: 'Accès complet à la modélisation de base, analyse statique linéaire OpenSees et outils pour étudiants, chercheurs et passionnés.',
    popular: false,
    ctaTextEn: 'Download Community',
    ctaTextFr: 'Télécharger Community',
    ctaLink: '/downloads',
    features: [
      { textEn: 'Full 3D Structural Modeling (Nodes, Beams, Columns)', textFr: 'Modélisation structurale 3D complète (Nœuds, Poutres, Poteaux)', included: true },
      { textEn: 'Standard Cross-Sections & Materials Library', textFr: 'Bibliothèque de sections et matériaux standards', included: true },
      { textEn: 'OpenSees Linear Static & Modal Analysis', textFr: 'Analyse linéaire statique et modale OpenSees', included: true },
      { textEn: 'Displacements, Internal Forces (N, V, M) Diagrams', textFr: 'Diagrammes de déplacements et efforts internes (N, V, M)', included: true },
      { textEn: 'TSALib Standard Dynamic Libraries', textFr: 'Bibliothèques dynamiques standard TSALib', included: true },
      { textEn: 'BIM IFC 4.3 Export / Import', textFr: 'Export / Import BIM IFC 4.3', included: false, noteEn: 'Planned in Pro', noteFr: 'Prévu en Pro' },
      { textEn: 'Nonlinear Dynamic & Pushover Analysis', textFr: 'Analyse non-linéaire dynamique et Pushover', included: false },
      { textEn: 'Co-Engineering AI Assistant (Cloud/Local)', textFr: 'Assistant Co-Engineering IA (Cloud/Local)', included: false, noteEn: 'In Development', noteFr: 'En cours de développement' },
      { textEn: 'Commercial Consulting Support', textFr: 'Support pour projets commerciaux', included: false },
    ],
  },
  {
    id: 'professional',
    name: 'Professional',
    nameFr: 'Professionnel',
    badgeEn: 'Most Popular for Engineers',
    badgeFr: 'Le plus adapté aux Ingénieurs',
    priceEn: 'To be announced',
    priceFr: 'À définir',
    periodEn: 'Per seat / Annual',
    periodFr: 'Par poste / Annuel',
    descriptionEn: 'Engineered for consulting civil engineers and design offices requiring automated meshing, non-linear analysis, and code verifications.',
    descriptionFr: 'Conçu pour les ingénieurs d\'études et bureaux de calcul nécessitant un maillage automatisé, analyse non-linéaire et vérifications normatives.',
    popular: true,
    ctaTextEn: 'Join Pre-release Waitlist',
    ctaTextFr: 'Rejoindre la liste d\'attente',
    ctaLink: '/about',
    features: [
      { textEn: 'Everything in Community Edition', textFr: 'Tout le contenu de l\'édition Community', included: true },
      { textEn: 'Advanced Automated Shell & Plate Meshing', textFr: 'Maillage automatique avancé de plaques et coques', included: true },
      { textEn: 'OpenSees P-Delta & Non-linear Inelastic Analysis', textFr: 'Analyse non-linéaire OpenSees et effets P-Delta', included: true },
      { textEn: 'Eurocodes (EN 1992, EN 1993) & AISC Checking Modules', textFr: 'Modules de vérification Eurocodes (EN 1992, EN 1993) & AISC', included: true },
      { textEn: 'BIM IFC Structural Analysis Model Interoperability', textFr: 'Interopérabilité BIM IFC Structural Analysis Model', included: true },
      { textEn: 'Automated Calculation Reports Generation (PDF / Markdown)', textFr: 'Génération automatisée de notes de calcul (PDF / Markdown)', included: true },
      { textEn: 'Co-Engineering AI Assistant (Standard Tier)', textFr: 'Assistant Co-Engineering IA (Niveau standard)', included: true },
      { textEn: 'Priority Technical Support', textFr: 'Support technique prioritaire', included: true },
      { textEn: 'Multi-seat Floating Network License', textFr: 'Licence réseau flottante multi-postes', included: false, noteEn: 'Available in Enterprise', noteFr: 'Disponible en Entreprise' },
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    nameFr: 'Entreprise',
    badgeEn: 'Firms & Institutions',
    badgeFr: 'Grands Comptes & Laboratoires',
    priceEn: 'On request',
    priceFr: 'Sur devis',
    periodEn: 'Custom Deployment',
    periodFr: 'Déploiement sur mesure',
    descriptionEn: 'Tailored for large multidisciplinary engineering firms, university research labs, and sovereign infrastructure projects.',
    descriptionFr: 'Pour les grands bureaux d\'études multidisciplinaires, laboratoires universitaires et gestionnaires d\'infrastructures.',
    popular: false,
    ctaTextEn: 'Contact Us',
    ctaTextFr: 'Nous contacter',
    ctaLink: '/about',
    features: [
      { textEn: 'Everything in Professional Edition', textFr: 'Tout le contenu de l\'édition Professionnel', included: true },
      { textEn: 'Floating License Server & Offline Dongle Options', textFr: 'Serveur de licences flottantes & options clés matérielles', included: true },
      { textEn: 'Custom TSALib Solvers & Proprietary Section Plugins', textFr: 'Solveurs personnalisés TSALib & plugins de sections propriétaires', included: true },
      { textEn: 'High-Performance Cluster / Distributed OpenSees Solving', textFr: 'Calcul OpenSees distribué sur grappe haute performance', included: true },
      { textEn: 'Private On-Premise Co-Engineering AI Model Deployment', textFr: 'Déploiement privé On-Premise de l\'assistant Co-Engineering IA', included: true },
      { textEn: 'SLA Guarantee & Dedicated Engineering Account Manager', textFr: 'Garantie SLA & Ingénieur d\'application dédié', included: true },
      { textEn: 'Bespoke Custom Training & Workflow Consulting', textFr: 'Formations sur mesure & intégration de flux de travail', included: true },
    ],
  },
];
