import { RoadmapItem } from '../types';

export const roadmapItems: RoadmapItem[] = [
  // --- Completed ---
  {
    id: 'road-core-3d',
    titleEn: 'Core 3D Structural Modeling Kernel',
    titleFr: 'Noyau de Modélisation Structurale 3D',
    descriptionEn: 'Full 3D object model supporting nodes, beams, columns, truss elements, and cable members with OpenCASCADE visualization.',
    descriptionFr: 'Modèle objet 3D complet gérant nœuds, poutres, poteaux, treillis et câbles avec affichage OpenCASCADE.',
    status: 'completed',
    quarter: 'Q1-Q2 2026',
    tags: ['Core', 'C++20', 'OCCT'],
  },
  {
    id: 'road-tsalib',
    titleEn: 'TSALib Dynamic Extension Architecture',
    titleFr: 'Architecture d\'Extensions Dynamiques TSALib',
    descriptionEn: 'Modular hot-reloadable library mechanism for cross-section catalogs, custom material formulations, and external plugin routines.',
    descriptionFr: 'Mécanisme d\'extensions modulaires chargeable à chaud pour catalogues de sections, lois de matériaux et plugins.',
    status: 'completed',
    quarter: 'Q2 2026',
    tags: ['TSALib', 'Extensibility', 'Modular'],
  },
  {
    id: 'road-opensees-bridge',
    titleEn: 'OpenSees Linear Static Bridge',
    titleFr: 'Passerelle OpenSees Statique Linéaire',
    descriptionEn: 'Automated translation from TSA structural model to OpenSees solver, execution management, and nodal displacement extraction.',
    descriptionFr: 'Traduction automatique du modèle structural vers OpenSees, exécution du solveur et extraction des déplacements.',
    status: 'completed',
    quarter: 'Q3 2026',
    tags: ['OpenSees', 'FEM', 'Solvers'],
  },
  {
    id: 'road-workplanes',
    titleEn: 'Parametric WorkPlanes & Grids',
    titleFr: 'Plans de Travail Paramétriques & Grilles',
    descriptionEn: 'Interactive coordinate reference systems with magnetic snapping, elevation levels, and customizable story planes.',
    descriptionFr: 'Systèmes de référence interactifs avec accrochage magnétique, niveaux d\'étages et plans de construction personnalisables.',
    status: 'completed',
    quarter: 'Q3 2026',
    tags: ['CAD', 'Grids', 'WorkPlane'],
  },

  // --- In Development ---
  {
    id: 'road-shell-meshing',
    titleEn: 'Automated 2D Plate & Shell Meshing',
    titleFr: 'Maillage Automatique de Plaques & Coques 2D',
    descriptionEn: 'Robust triangular and quadrilateral discretization of slabs, wall panels, and diaphragms with boundary conforming mesh generators.',
    descriptionFr: 'Discrétisation triangulaire et quadrangulaire de dalles et voiles avec respect strict des contours et ouvertures.',
    status: 'in_development',
    quarter: 'Q4 2026',
    tags: ['Meshing', 'Slabs', 'FEM'],
  },
  {
    id: 'road-modal-dynamics',
    titleEn: 'Modal Dynamics & Seismic Spectrum',
    titleFr: 'Dynamique Modale & Spectres Sismiques',
    descriptionEn: 'Eigenmode decomposition, modal participation masses, and response spectrum analysis conforming to Eurocode 8 requirements.',
    descriptionFr: 'Calcul des modes propres, masses modales effectives et analyse spectrale sismique selon les exigences Eurocode 8.',
    status: 'in_development',
    quarter: 'Q4 2026',
    tags: ['Dynamics', 'Seismic', 'Eurocode 8'],
  },
  {
    id: 'road-diagrams-3d',
    titleEn: 'Interactive 3D Moment & Shear Envelopes',
    titleFr: 'Enveloppes 3D Interactives de Moments & Tranchants',
    descriptionEn: 'GPU-accelerated rendering of internal force diagrams (N, Vy, Vz, Mt, My, Mz) directly overlaid on structural wires in viewport.',
    descriptionFr: 'Rendu accéléré par GPU des diagrammes d\'efforts internes directement superposés aux barres dans la vue 3D.',
    status: 'in_development',
    quarter: 'Q4 2026',
    tags: ['Graphics', 'PostProcessing', 'Envelopes'],
  },

  // --- Planned ---
  {
    id: 'road-bim-ifc',
    titleEn: 'BIM IFC 4.3 Structural Analysis Model',
    titleFr: 'Modèle BIM d\'Analyse Structurale IFC 4.3',
    descriptionEn: 'Full round-trip import and export of IfcStructuralCurveMember, IfcStructuralSurfaceMember, supports, and associated loads.',
    descriptionFr: 'Import/export complet d\'éléments structuraux IFC, conditions d\'appuis et cas de charges normalisés.',
    status: 'planned',
    quarter: 'Q1 2027',
    tags: ['BIM', 'IFC', 'Interoperability'],
  },
  {
    id: 'road-co-eng-assistant',
    titleEn: 'Co-Engineering AI Structural Assistant',
    titleFr: 'Assistant Co-Engineering IA en Ingénierie',
    descriptionEn: 'Context-aware engineering assistant providing modeling assistance, mesh diagnostics, load path verification, and code sanity checks.',
    descriptionFr: 'Assistant d\'ingénierie contextuel pour l\'aide à la saisie, diagnostic de maillage et vérification du cheminement des charges.',
    status: 'planned',
    quarter: 'Q1-Q2 2027',
    tags: ['AI', 'CoEngineering', 'Diagnostics'],
  },
  {
    id: 'road-automated-reports',
    titleEn: 'Standardized Engineering Calculation Reports',
    titleFr: 'Génération de Notes de Calcul Réglementaires',
    descriptionEn: 'One-click publication of professional calculation notes with equation traces, design assumptions, load tables, and 3D views.',
    descriptionFr: 'Édition en un clic de notes de calcul professionnelles avec traçabilité des formules, hypothèses et extraits graphiques.',
    status: 'planned',
    quarter: 'Q2 2027',
    tags: ['Reporting', 'Eurocodes', 'Documentation'],
  },

  // --- Research ---
  {
    id: 'road-nonlinear-concrete',
    titleEn: 'Inelastic Reinforced Concrete Fiber Sections',
    titleFr: 'Modélisation Fibres Béton Armé Non-Linéaire',
    descriptionEn: 'Distributed plasticity fiber beam-column elements using Kent-Park concrete and Giuffre-Menegotto-Pinto reinforcing steel models in OpenSees.',
    descriptionFr: 'Éléments à plasticité distribuée en fibres avec lois de comportement de Kent-Park et Menegotto-Pinto dans OpenSees.',
    status: 'research',
    quarter: 'H2 2027',
    tags: ['Research', 'Fibers', 'Nonlinear'],
  },
  {
    id: 'road-cloud-cluster',
    titleEn: 'Cloud Distributed Cluster Solving',
    titleFr: 'Calcul Haute Performance Distribué sur Cloud',
    descriptionEn: 'High-throughput parametric sensitivity studies and non-linear time-history runs executed over parallel cloud clusters.',
    descriptionFr: 'Études de sensibilité paramétrique et analyses temporelles non-linéaires exécutées en parallèle sur clusters cloud.',
    status: 'research',
    quarter: 'H2 2027',
    tags: ['Cloud', 'HPC', 'Parallel'],
  },
];
